grails-app/controllers/volp/EntranceApplicationApprovalController.groovy
package volp

class EntranceApplicationApprovalController {

    def index() { }

    def addApplicationApproval(){
        if (session.loginid == null) {
            flash.message = "Your are logged out! Please login again. Thank you."
            redirect(controller: "login", action: "erplogin")
            return
        } else {
            println("addApplicationApproval : " + params)
            Login login = Login.findById(session.loginid)
            Instructor instructor = Instructor.findByUid(login.username)
            Organization org = instructor.organization

            def entranceBranch_list = EntranceBranch.findAllByOrganization(org)
            def entranceVersion_list = EntranceVersion.findAllByOrganization(org)

            [entranceBranch_list:entranceBranch_list,entranceVersion_list:entranceVersion_list]
        }
    }
    def getApplicationToapproval(){
        if (session.loginid == null) {
            flash.message = "Your are logged out! Please login again. Thank you."
            redirect(controller: "login", action: "erplogin")
            return
        } else {
            println("getApplicationToapproval : " + params)
            Login login = Login.findById(session.loginid)
            Instructor instructor = Instructor.findByUid(login.username)
            Organization org = instructor.organization

            def entranceApplicationStatus_list = EntranceApplicationStatus.findAllByOrganization(org)
            def exemption_list = Exemption.findAllByOrganization(org)
            //EntranceBranch entranceBranch = EntranceBranch.findByName(params.branch)
            EntranceVersion entranceVersion = EntranceVersion.findById(params.entranceVersionId)
            def entranceBranch = EntranceBranch.findByName(params.branch)
            println("entranceBranch : "+entranceBranch)
            def  entranceBranch1 = EntranceBranch.findAllByEntranceversion(entranceVersion)
            println("entranceBranch1: "+entranceBranch1)
            def entranceApplicationStatus = EntranceApplicationStatus.findByName('In-Process')
            def entranceApplication_list = EntranceApplication.findAllByEntranceversionAndEntranceapplicationstatus(entranceVersion,entranceApplicationStatus)
            //def entranceApplication_list = EntranceApplication.findAllByEntranceversionAndEntrancebranch(entranceVersion,entranceBranch)
            println("entranceApplication_list : "+entranceApplication_list)
            def entranceRejectionReason_list = EntranceRejectionReason.findAllByOrganization(org)


            [entranceVersion:entranceVersion,entranceApplication_list:entranceApplication_list,entranceApplicationStatus_list:entranceApplicationStatus_list,
             exemption_list:exemption_list,branch:params.branch,entranceRejectionReason_list:entranceRejectionReason_list]
        }
    }
    def saveApplicationToapproval(){
        if (session.loginid == null) {
            flash.message = "Your are logged out! Please login again. Thank you."
            redirect(controller: "login", action: "erplogin")
            return
        }else {
            println("In saveApplicationToapproval : " + params)
            Login login = Login.findById(session.loginid)
            Instructor instructor = Instructor.findByUid(login.username)
            Organization org = instructor.organization

            EntranceApplication entranceApplication = EntranceApplication.findById(params.entranceApplicationId)
            println("entranceApplication : "+entranceApplication)
            EntranceApplicationStatus entranceApplicationStatus = EntranceApplicationStatus.findByName(params.applicationStatus)
            Exemption exemption = Exemption.findByName(params.exemption)
            EntranceRejectionReason entranceRejectionReason = EntranceRejectionReason.findByName(params.rejectionReason)
            if(entranceApplication)
            {
                entranceApplication.entranceapplicationstatus = entranceApplicationStatus
                entranceApplication.entranceapplicant.exemption = exemption
                entranceApplication.entrancerejectionreason = entranceRejectionReason
                entranceApplication.actionby = instructor
                entranceApplication.updation_username = instructor.uid
                entranceApplication.updation_ip_address = request.getRemoteAddr()
                entranceApplication.updation_date = new java.util.Date()
                entranceApplication.save(flush: true, failOnError: true)
                flash.message = "Saved Successfully"
                redirect(action: 'getApplicationToapproval')
            }else {
                flash.error = "Already Exists..."
                redirect(action:'getApplicationToapproval')
            }
        }

    }
    def viewApplicationInApproval(){
        if (session.loginid == null) {
            flash.message = "Your are logged out! Please login again. Thank you."
            redirect(controller: "login", action: "erplogin")
            return
        }else {
            def array=[]
            println("In viewApplicationInApproval"+ params)
            Login login = Login.findById(session.loginid)
            Instructor instructor = Instructor.findByUid(login.username)
            Organization org = instructor.organization

            EntranceVersion entranceVersion = EntranceVersion.findById(params.entranceVersion)
            EntranceApplicant entranceApplicant= EntranceApplicant.findById(params.applicantId)
            EntranceApplication entranceApplication = EntranceApplication.findByEntranceapplicantAndEntranceversion(entranceApplicant,entranceVersion)
            def entranceApplicantAcademics = EntranceApplicantAcademics.findAllByEntranceapplicantAndOrganization(entranceApplicant,org)
            def entranceApplicantExperience = EntranceApplicantExperience.findAllByEntranceapplicantAndOrganization(entranceApplicant,org)
            def entranceApplicantDocument = EntranceApplicantDocument.findAllByEntranceapplicantAndOrganization(entranceApplicant,org)
            AWSFolderPath awsFolderPath = AWSFolderPath.findById('5')
            AWSBucket awsBucket = AWSBucket.findByContent("documents")
            AWSBucketService awsBucketService = new AWSBucketService()
            for(doc in entranceApplicantDocument)
            {
                HashMap hm=new HashMap()
                def awsimagelink = doc?.filepath + doc?.filename
                String file = awsBucketService.getPresignedUrl(awsBucket.bucketname,awsimagelink, awsBucket.region)
                hm.put("url",file)
                hm.put("document",doc)
                array.add(hm)
            }
            String file = "https://vierp-test.s3.ap-south-1.amazonaws.com/img_avatar.png";
            if(entranceApplicant && entranceApplicant?.photopath && entranceApplicant.photoname) {
                def awsimagelink = entranceApplicant.photopath + entranceApplicant.photoname
                file = awsBucketService.getPresignedUrl(awsBucket.bucketname, awsimagelink, awsBucket.region)
            }
            [Photo_URL:file,EA:entranceApplicant,entranceApplication: entranceApplication,entranceApplicantAcademics:entranceApplicantAcademics,
             entranceApplicantExperience:entranceApplicantExperience,entranceApplicantDocument:array]
        }
    }
    def getApplicationCount(){
        println("in getApplicationCount "+params)
        EntranceVersion entranceVersion = EntranceVersion.findById(params.versionId)
        def entranceApplication_list = EntranceApplication.findAllByEntranceversion(entranceVersion)
        def entranceApplication_list_count= entranceApplication_list.size()
        render entranceApplication_list_count
        return
    }
    def getShortListedApplicationCount(){
        println("in getApplicationCount "+params)
        EntranceVersion entranceVersion = EntranceVersion.findById(params.versionId)
        EntranceApplicationStatus entranceApplicationStatus = EntranceApplicationStatus.findByName('Accepted')
        def entranceApplication_list = EntranceApplication.findAllByEntranceversionAndEntranceapplicationstatus(entranceVersion,entranceApplicationStatus)
        def entranceApplication_list_count= entranceApplication_list.size()
        render entranceApplication_list_count
        return
    }


    //Exemption Approval
    def addExemptionApproval(){
        if (session.loginid == null) {
            flash.message = "Your are logged out! Please login again. Thank you."
            redirect(controller: "login", action: "erplogin")
            return
        } else {
            println("addExemptionApproval : " + params)
            Login login = Login.findById(session.loginid)
            Instructor instructor = Instructor.findByUid(login.username)
            Organization org = instructor.organization

            def entranceApplication_list = EntranceApplication.findAllByOrganization(org)
            def exemption_list = Exemption.findAllByOrganization(org)

            [entranceApplication_list:entranceApplication_list,exemption_list:exemption_list]
        }
    }
    def saveExemptionApproval(){
        if (session.loginid == null) {
            flash.message = "Your are logged out! Please login again. Thank you."
            redirect(controller: "login", action: "erplogin")
            return
        } else {
            println("saveExemptionApproval : " + params)
            Login login = Login.findById(session.loginid)
            Instructor instructor = Instructor.findByUid(login.username)
            Organization org = instructor.organization

            EntranceApplication entranceApplication = EntranceApplication.findById(params.applicationId)
            Exemption exemption = Exemption.findByName(params.exemption)
            if(entranceApplication){
                entranceApplication.exemption = exemption
                if(params.exemption == 'Not-exempted'){

grails-app/views/entranceApplicationApproval/addApplicationApproval.gsp
<!doctype html>
<html>
    <head>
         <meta name="layout" content="smart_main_datatable_inst"/>
        <meta name="author" content="reena"/>
         <style>
            .fabutton {
                  background: none;
                  padding: 0px;
                  border: none;
            }
        </style>
    </head>
    <body>
        <!-- start page content -->
        <div class="page-content-wrapper">
            <div class="page-content">
             <div class="page-bar">
                <g:render template="/layouts/smart_template_inst/breadcrumb" />

                <!-- add content here -->
                <g:if test="${flash.message}">
                     <div class="alert alert-success" >${flash.message}</div>
                </g:if>
                <g:if test="${flash.error}">
                     <div class="alert alert-danger" >${flash.error}</div>
                </g:if>

                <!--////-->
                <!--Table,Edit,Delete-->

                            <div class="row">
                               <div class="col-md-12  mobile-table-responsive">
                                   <div class="card card-topline-purple">
                                       <div class="card-head">
                                           <header class="erp-table-header">Entrance Version Details</header>
                                       </div>
                                        <div class="table-responsive">
                                            <table id="exportTable" class="display nowrap erp-full-width table-striped  table-hover ml-table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th class="mdl-data-table__cell--non-numeric">Sr. No.</th>
                                                        <th class="mdl-data-table__cell--non-numeric">Academic Year</th>
                                                        <th class="mdl-data-table__cell--non-numeric">Program Type</th>
                                                        <th class="mdl-data-table__cell--non-numeric">Entrance Name</th>
                                                        <th class="mdl-data-table__cell--non-numeric">Total Applications</th>
                                                        <th class="mdl-data-table__cell--non-numeric">Shortlisted Applications</th>
                                                        <th class="mdl-data-table__cell--non-numeric">Branch</th>
                                                        <th class="mdl-data-table__cell--non-numeric">Proceed To Approval</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <g:each in="${entranceVersion_list}" var="name" status="i">
                                                        <tr>
                                                            <td class="mdl-data-table__cell--non-numeric">${i+1}</td>
                                                            <td class="mdl-data-table__cell--non-numeric">${name?.academicyear}</td>
                                                            <td class="mdl-data-table__cell--non-numeric">${name?.programtype?.name}</td>
                                                            <td class="mdl-data-table__cell--non-numeric">${name?.entrance_name}</td>
                                                            <td class="mdl-data-table__cell--non-numeric">
                                                                <g:include controller="entranceApplicationApproval" action="getApplicationCount" params="[versionId:name?.id]" />
                                                            </td>
                                                            <td class="mdl-data-table__cell--non-numeric">
                                                                <g:include controller="entranceApplicationApproval" action="getShortListedApplicationCount" params="[versionId:name?.id]" />
                                                            </td>

                                                            <g:form action="getApplicationToapproval">
                                                            <td class="form-group">
                                                              <g:select name="branch" id="branch"  from="${entranceBranch_list?.name}"
                                                              style="width: 90% !important;"  class="select2"
                                                              optionValue="${branch}"
                                                              noSelection="['null':'Please Select Branch']"/>
                                                            </td>
                                                            <td class="mdl-data-table__cell--non-numeric form-group"">
                                                                 <input type="hidden" value="${name?.id}" name="entranceVersionId">
                                                                  <button type="submit" class="btn btn-primary">Proceed</button>
                                                            </td>
                                                            </g:form>
                                                        </tr>
                                                    </g:each>
                                                </tbody>
                                            </table>
                                        </div>
                                     </div>
                                </div>
                             </div>
                        </div>
                    </div>
        </div>
    </body>
</html>

grails-app/views/entranceApplicationApproval/addExemptionApproval.gsp
<!doctype html>
<html>
    <head>
         <meta name="layout" content="smart_main_datatable_inst"/>
        <meta name="author" content="reena"/>
         <style>
            .fabutton {
                  background: none;
                  padding: 0px;
                  border: none;
            }
        </style>
    </head>
    <body>
        <!-- start page content -->
        <div class="page-content-wrapper">
            <div class="page-content">
             <div class="page-bar">
                <g:render template="/layouts/smart_template_inst/breadcrumb" />

                <!-- add content here -->
                <g:if test="${flash.message}">
                     <div class="alert alert-success" >${flash.message}</div>
                </g:if>
                <g:if test="${flash.error}">
                     <div class="alert alert-danger" >${flash.error}</div>
                </g:if>

                <!--////-->
                <!--Table,Edit,Delete-->

                            <div class="row">
                               <div class="col-md-12  mobile-table-responsive">
                                   <div class="card card-topline-purple">
                                       <div class="card-head">
                                           <header class="erp-table-header">Exemption Approval</header>
                                       </div>
                                            <div class="table-responsive">
                                                <table id="exportTable" class="display nowrap erp-full-width table-striped  table-hover ml-table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th class="mdl-data-table__cell--non-numeric">Sr. No.</th>
                                                            <th class="mdl-data-table__cell--non-numeric">Applicant Name</th>
                                                            <th class="mdl-data-table__cell--non-numeric">Exemption</th>
                                                            <th class="mdl-data-table__cell--non-numeric">Exemption Type Details</th>
                                                            <th class="mdl-data-table__cell--non-numeric">Save</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <g:each in="${entranceApplication_list}" var="name" status="i">
                                                            <tr>
                                                                <td class="mdl-data-table__cell--non-numeric">${i+1}</td>
                                                                <td class="mdl-data-table__cell--non-numeric">${name?.entranceapplicant?.fullname}</td>
                                                                <g:form action="saveExemptionApproval">
                                                                <td class="mdl-data-table__cell--non-numeric form-group">
                                                                   <g:select name="exemption" from="${exemption_list?.name}" style="width: 100% !important;"  class="select2" required="true"
                                                                   value="${name?.exemption?.name}"  noSelection="['null':'Select Exemption']"/><br>
                                                                </td>
                                                                <td class="mdl-data-table__cell--non-numeric">
                                                                   <div class="table-responsive ">
                                                                       <table id="exportTable" class="display nowrap erp-full-width ml-table-bordered" >
                                                                           <thead>
                                                                               <tr>
                                                                                   <th class="mdl-data-table__cell--non-numeric">Sr. No.</th>
                                                                                   <th class="mdl-data-table__cell--non-numeric">Exemption Type</th>
                                                                                   <th class="mdl-data-table__cell--non-numeric">Download</th>
                                                                               </tr>
                                                                           </thead>
                                                                           <tbody>
                                                                               <g:each in="${name?.exemptiontype}" var="exemptionType" status="k">
                                                                                   <tr>
                                                                                       <td class="mdl-data-table__cell--non-numeric">${k+1}</td>
                                                                                       <td class="mdl-data-table__cell--non-numeric">${exemptionType?.name}</td>
                                                                                       <td class="mdl-data-table__cell--non-numeric">
                                                                                           <g:include controller="entranceApplicationApproval" action="getExemptionTypedocumenturl" params="[exemptionTypeId:exemptionType?.id,applicationId:name?.id]" />
                                                                                       </td>
                                                                                   </tr>
                                                                               </g:each>
                                                                           </tbody>
                                                                       </table>
                                                                   </div>
                                                                </td>
                                                                <td class="mdl-data-table__cell--non-numeric form-group">
                                                                    <input type="hidden" name="applicationId" id="applicationId" value="${name?.id}"/>
                                                                    <button type="submit" class="btn btn-primary" > <span class="glyphicon glyphicon-save"></span>Save</button>
                                                                </td>
                                                                </g:form>
                                                            </tr>
                                                        </g:each>
                                                    </tbody>
                                                </table>
                                            </div>
                                     </div>
                                </div>
                             </div>
                        </div>
                    </div>
        </div>
    </body>
</html>